export enum productConst {
  FETCH_PRODUCT_COUNTS_REQUEST = "FETCH_PRODUCT_COUNTS_REQUEST",
  FETCH_PRODUCT_COUNTS_SUCCESS = "FETCH_PRODUCT_COUNTS_SUCCESS",
  FETCH_PRODUCT_COUNTS_FAILURE = "FETCH_PRODUCT_COUNTS_FAILURE",
  FETCH_PRODUCT_STATUS_COUNTS_REQUEST = "FETCH_PRODUCT_STATUS_COUNTS_REQUEST",
  FETCH_PRODUCT_STATUS_COUNTS_SUCCESS = "FETCH_PRODUCT_STATUS_COUNTS_SUCCESS",
  FETCH_PRODUCT_STATUS_COUNTS_FAILURE = "FETCH_PRODUCT_STATUS_COUNTS_FAILURE",
}
