export enum accessoryKeys {
  CHECK_IN_ACCESSORY = "CHECK_IN_ACCESSORY",
  CHECK_OUT_ACCESSORY = "CHECK_OUT_ACCESSORY",
}

export enum assetKeys {
  CHECK_IN_ASSET = "CHECK_IN_ASSET",
  CHECK_OUT_ASSET = "CHECK_OUT_ASSET",
}

export enum componentKeys {
  CHECK_IN_COMPONENT = "CHECK_IN_COMPONENT",
  CHECK_OUT_COMPONENT = "CHECK_OUT_COMPONENT",
}

export enum consumableKeys {
  CHECK_IN_CONSUMABLE = "CHECK_IN_CONSUMABLE",
  CHECK_OUT_CONSUMABLE = "CHECK_OUT_CONSUMABLE",
}

export enum licenseKeys {
  USER_CHECK_IN_LICENSE = "USER_CHECK_IN_LICENSE",
  USER_CHECK_OUT_LICENSE = "USER_CHECK_OUT_LICENSE",
  ASSET_CHECK_IN_LICENSE = "ASSET_CHECK_IN_LICENSE",
  ASSET_CHECK_OUT_LICENSE = "ASSET_CHECK_OUT_LICENSE",
}

export enum permissionKeys {
  SYNC_PERMISSIONS = "SYNC_PERMISSIONS",
}

export enum productKeys {
  FETCH_PRODUCT_COUNTS = "FETCH_PRODUCT_COUNTS",
  FETCH_PRODUCT_STATUS_COUNTS = "FETCH_PRODUCT_STATUS_COUNTS",
  FETCH_PRODUCT_LOCATION_COUNTS = "FETCH_PRODUCT_LOCATION_COUNTS",
  FETCH_PRODUCT_CATEGORY_COUNTS = "FETCH_PRODUCT_CATEGORY_COUNTS",
  FETCH_CUSTOM_LOGS = "FETCH_CUSTOM_LOGS",
}

export enum userKeys {
  SIGN_IN_USER = "SIGN_IN_USER",
  GET_WITH_TOKEN_USER = "GET_WITH_TOKEN_USER",
}
