export enum genericConst {
  SET_LOADING = "SET_LOADING",
  RESET_LOADING = "CLEAR_LOADING",
  INCREASE_LOADING = "INCREASE_LOADING",
  DECREASE_LOADING = "DECREASE_LOADING",
  SET_ERROR = "SET_ERROR",
  CLEAR_ERROR = "CLEAR_ERROR",
}
