version: '3.4'

services:
  stocklinx.api:
    image: ${DOCKER_REGISTRY-}stocklinxapi
    container_name: stocklinx.api
    build:
      context: .
      dockerfile: StockLinx.API/Dockerfile
    ports:
      - "5007:5007"
      - "5008:5008" 

  stocklinx.database:
    image: postgres:latest
    container_name: stocklinx.database
    restart: always
    environment:
      - POSTGRES_DB=StockLinxDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=372978
    volumes:
      - ./.containers/stocklinx-db:/var/lib/postgresql/data
    ports:
      - 6543:5432

  stocklinx.client:
    image: ${DOCKER_REGISTRY-}stocklinxclient
    container_name: stocklinx.client
    build:
      context: ../client
      dockerfile: Dockerfile
  proxy:
    image: nginx:mainline
