version: '3.4'

services:
  stocklinx.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5007
      - ASPNETCORE_HTTPS_PORTS=5008
    ports:
      - "5007:5007"
      - "5008:5008"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  stocklinx.client:
    ports:
      - "5173:5173"
  proxy:
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    